  
name: Self Test

on: [push]

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: teaminkling/skip-commit@master
        with:
          commit-filter: skip-ci
      - uses: teaminkling/autoversion@master
        with:
          managers: npm
      - uses: teaminkling/autobadger@master
      - uses: teaminkling/automilestone@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
